import { z } from 'zod';
export * from './usage.js';

import { ConnectorState } from './usage.js';

export const Freshness = z.enum(['fresh','stale','unknown']);
export const Quality = z.enum(['observed','estimated','partial','unavailable']);
export const Provenance = z.object({ source: z.string().min(1), observedAt: z.string().datetime({ offset: true }), freshness: Freshness, quality: Quality, connectorState: ConnectorState });
export type Provenance = z.infer<typeof Provenance>;
export const Metric = z.object({ value: z.number().finite(), unit: z.string().min(1), provenance: Provenance });
export const Overview = z.object({ kind: z.literal('overview'), label: z.literal('Demo data'), generatedAt: z.string().datetime({ offset: true }), codex: z.object({ status: z.string(), usage5h: Metric, usageWeek: Metric }), connectors: z.record(ConnectorState) });
export const CodexFixture = z.object({ kind: z.literal('codex'), label: z.literal('Demo data'), generatedAt: z.string().datetime({ offset: true }), session: z.object({ status: z.string(), model: z.string(), workspace: z.string(), active: z.boolean() }), usage: z.object({ fiveHour: Metric, weekly: Metric }), trend: z.array(z.object({ at: z.string().datetime({ offset: true }), value: z.number().finite(), provenance: Provenance })), estimate: z.object({ range: z.string(), confidence: z.number().min(0).max(1), explanation: z.string(), provenance: Provenance }) });
export type Overview = z.infer<typeof Overview>; export type CodexFixture = z.infer<typeof CodexFixture>;
export function freshnessFromObservedAt(observedAt: string, now = Date.now()): 'fresh'|'stale'|'unknown' { const age = now - Date.parse(observedAt); if (!Number.isFinite(age) || age < 0) return 'unknown'; return age <= 15 * 60_000 ? 'fresh' : 'stale'; }
export const fixtures = { overview: { kind:'overview', label:'Demo data', generatedAt:'2026-07-28T12:00:00+00:00', codex:{status:'active',usage5h:{value:42,unit:'%',provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'observed',connectorState:'healthy'}},usageWeek:{value:31,unit:'%',provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'observed',connectorState:'healthy'}}},connectors:{codex:'healthy',clipper:'unavailable',health:'unavailable',finance:'unavailable'} }, codex: { kind:'codex',label:'Demo data',generatedAt:'2026-07-28T12:00:00+00:00',session:{status:'active',model:'demo-model',workspace:'demo-workspace',active:true},usage:{fiveHour:{value:42,unit:'%',provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'observed',connectorState:'healthy'}},weekly:{value:31,unit:'%',provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'observed',connectorState:'healthy'}}},trend:[{at:'2026-07-28T10:00:00+00:00',value:38,provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'observed',connectorState:'healthy'}}],estimate:{range:'2–4 hours',confidence:.6,explanation:'Demo estimate based on fixture trend; not an official quota.',provenance:{source:'demo-codex-fixture',observedAt:'2026-07-28T11:55:00+00:00',freshness:'fresh',quality:'estimated',connectorState:'healthy'}} } };
export function parseOverview(input: unknown) { return Overview.parse(input); } export function parseCodexFixture(input: unknown) { return CodexFixture.parse(input); }
