import Foundation

public struct TaxEvidence: Codable, Equatable, Sendable { public let page: Int; public let snippet: String; public init(page: Int, snippet: String) { self.page = page; self.snippet = snippet } }
public struct TaxDate: Codable, Equatable, Sendable { public var value: String; public var evidence: TaxEvidence; public init(value: String, evidence: TaxEvidence) { self.value=value; self.evidence=evidence } }
public struct TaxAmount: Codable, Equatable, Sendable { public var value: String; public var label: String; public var evidence: TaxEvidence; public init(value: String,label: String,evidence: TaxEvidence){self.value=value;self.label=label;self.evidence=evidence} }
public struct TaxCandidate: Codable, Equatable, Sendable { public var value: String; public var evidence: TaxEvidence; public init(value:String,evidence:TaxEvidence){self.value=value;self.evidence=evidence} }
public enum TaxConfidence: String, Codable, Sendable { case low, medium, high }

public struct TaxDocument: Codable, Equatable, Identifiable, Sendable {
 public let id: UUID; public var title:String; public var documentType:String; public var taxYear:Int?; public var issuer:TaxCandidate?; public var taxpayerIdentifier:TaxCandidate?; public var referenceIdentifier:TaxCandidate?; public var dates:[TaxDate]; public var amounts:[TaxAmount]; public var pages:[String]; public var warnings:[String]; public var confidence:TaxConfidence
 public init(id:UUID=UUID(),title:String,documentType:String,taxYear:Int?,issuer:String?,taxpayerIdentifier:String?,referenceIdentifier:String?,dates:[TaxDate],amounts:[TaxAmount],pages:[String],warnings:[String]=[],confidence:TaxConfidence?=nil){self.id=id;self.title=title;self.documentType=documentType;self.taxYear=taxYear;self.dates=dates;self.amounts=amounts;self.pages=pages;self.warnings=warnings;self.confidence=confidence ?? TaxDocumentParser.confidence(taxYear:taxYear,issuer:issuer,taxpayerIdentifier:taxpayerIdentifier,referenceIdentifier:referenceIdentifier,dates:dates,amounts:amounts)}
 public init(id:UUID=UUID(),title:String,documentType:String,taxYear:Int?,issuer:TaxCandidate?,taxpayerIdentifier:TaxCandidate?,referenceIdentifier:TaxCandidate?,dates:[TaxDate],amounts:[TaxAmount],pages:[String],warnings:[String]=[],confidence:TaxConfidence?=nil){self.id=id;self.title=title;self.documentType=documentType;self.taxYear=taxYear;self.issuer=issuer;self.taxpayerIdentifier=taxpayerIdentifier;self.referenceIdentifier=referenceIdentifier;self.dates=dates;self.amounts=amounts;self.pages=pages;self.warnings=warnings;self.confidence=confidence ?? .low}
}

enum TaxDocumentParser {
 static func parse(text:String,documentName:String)->TaxDocument { parse(pages:[text],documentName:documentName) }
 static func parse(pages:[String],documentName:String)->TaxDocument {
  let clean=pages.map{$0.replacingOccurrences(of:"\u{FFFD}",with:"")}; var dates:[TaxDate]=[]; var amounts:[TaxAmount]=[]; var years:[Int]=[]
  let date=try? NSRegularExpression(pattern:#"\b(?:\d{1,2}[./]\d{1,2}[./]\d{4}|\d{4}-\d{2}-\d{2})\b"#); let money=try? NSRegularExpression(pattern:#"(?i)([\wÄÖÜäöüß -]{2,30}?)\s+([€$])?\s*(\d{1,3}(?:[. ]\d{3})*(?:,\d{2})|\d+(?:\.\d{2})?)\s*(EUR|€|USD|\$)?"#)
  for (i,text) in clean.enumerated(){ let ns=text as NSString; date?.enumerateMatches(in:text,range:NSRange(location:0,length:ns.length)){m,_,_ in guard let m else{return}; let v=ns.substring(with:m.range); dates.append(TaxDate(value:v,evidence:TaxEvidence(page:i+1,snippet:snippet(text,v)))) ; if let y=Int(String(v.suffix(4))), y>=1900 && y<=2100 { years.append(y) } }; money?.enumerateMatches(in:text,range:NSRange(location:0,length:ns.length)){m,_,_ in guard let m else{return}; let label=ns.substring(with:m.range(at:1)).trimmingCharacters(in:.whitespaces); let raw=ns.substring(with:m.range(at:3)); let value=raw.replacingOccurrences(of:".",with:"").replacingOccurrences(of:" ",with:"").replacingOccurrences(of:",",with:"."); amounts.append(TaxAmount(value:value,label:label,evidence:TaxEvidence(page:i+1,snippet:snippet(text,ns.substring(with:m.range)))))} }
  let all=clean.joined(separator:"\n"); let issuer=labelCandidate(all,labels:["Finanzamt","Issuer"]); let id=identifierCandidate(all); let ref=labelCandidate(all,labels:["Steuernummer","Aktenzeichen","Reference"]); var warnings:[String]=[]; if all.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty {warnings.append("No embedded text was found.")}; let year=years.first ?? (try? Int(NSRegularExpression(pattern:#"(?i)(?:Steuerjahr|tax year)\s*[:]?\s*(\d{4})"#).firstMatch(in:all,range:NSRange(location:0,length:(all as NSString).length)).map{(all as NSString).substring(with:$0.range(at:1))} ?? "")); return TaxDocument(title:documentName,documentType:documentName.replacingOccurrences(of:".pdf",with:"") ,taxYear:year,issuer:issuer,taxpayerIdentifier:id,referenceIdentifier:ref,dates:dates,amounts:amounts,pages:clean,warnings:warnings,confidence:confidence(taxYear:year,issuer:issuer?.value,taxpayerIdentifier:id?.value,referenceIdentifier:ref?.value,dates:dates,amounts:amounts))
 }
 private static func snippet(_ text:String,_ value:String)->String { text.replacingOccurrences(of:"\n"," ").prefix(240).description }
 private static func labelCandidate(_ text:String,labels:[String])->TaxCandidate? { guard let l=labels.first(where:{text.range(of:$0,options:.caseInsensitive) != nil}), let r=text.range(of:l,options:.caseInsensitive) else{return nil}; let s=String(text[r.lowerBound...]).split(separator:"\n").first.map(String.init) ?? l; return TaxCandidate(value:s,evidence:TaxEvidence(page:1,snippet:s)) }
 private static func identifierCandidate(_ text:String)->TaxCandidate? { let p=#"(?i)(?:steuer[- ]?nummer|tax id|id)[\s:]*([0-9A-Z][0-9A-Z /-]{3,})"#; guard let re=try? NSRegularExpression(pattern:p),let m=re.firstMatch(in:text,range:NSRange(location:0,length:(text as NSString).length)) else{return nil}; let raw=(text as NSString).substring(with:m.range(at:1)).trimmingCharacters(in:.whitespacesAndNewlines); guard raw.count>=4 else{return nil}; let masked=String(repeating:"*",count:max(0,raw.count-4))+raw.suffix(4); return TaxCandidate(value:masked,evidence:TaxEvidence(page:1,snippet:"identifier ending \(raw.suffix(4))")) }
 static func confidence(taxYear:Int?,issuer:String?,taxpayerIdentifier:String?,referenceIdentifier:String?,dates:[TaxDate],amounts:[TaxAmount])->TaxConfidence { let n=[taxYear != nil,issuer != nil,taxpayerIdentifier != nil,referenceIdentifier != nil,!dates.isEmpty,!amounts.isEmpty].filter{$0}.count; return n>=5 ? .high : n>=3 ? .medium : .low }
}

public struct TaxDocumentStore { let directory:URL; public init(directory:URL?=nil){ self.directory=directory ?? ((FileManager.default.containerURL(forSecurityApplicationGroupIdentifier:"group.com.nous.hermes") ?? FileManager.default.urls(for:.applicationSupportDirectory,in:.userDomainMask)[0]).appendingPathComponent("TaxDocuments",isDirectory:true)) }; private var file:URL {directory.appendingPathComponent("documents.json")}; public func load() throws->[TaxDocument]{guard FileManager.default.fileExists(atPath:file.path) else{return []}; return try JSONDecoder().decode([TaxDocument].self,from:Data(contentsOf:file))}; public func save(_ docs:[TaxDocument]) throws {try FileManager.default.createDirectory(at:directory,withIntermediateDirectories:true); let data=try JSONEncoder().encode(docs); let tmp=file.appendingPathExtension("tmp"); try data.write(to:tmp,options:.atomic); if FileManager.default.fileExists(atPath:file.path){try FileManager.default.removeItem(at:file)}; try FileManager.default.moveItem(at:tmp,to:file)} }
public enum TaxCSVExporter { public static func export(_ docs:[TaxDocument])->String { let rows=["title,document_type,tax_year,issuer,identifier,confidence"]+docs.map{[$0.title,$0.documentType,$0.taxYear.map(String.init) ?? "",$0.issuer?.value ?? "",$0.taxpayerIdentifier?.value ?? "",$0.confidence.rawValue].map{ "\"\($0.replacingOccurrences(of:"\"",with:"\"\""))\""}.joined(separator:",")}; return rows.joined(separator:"\n") } }
