import { useEffect, useState } from 'react';
import { parseCodexFixture, parseOverview, UnifiedUsage, type CodexFixture, type Overview, type Provider, type UsageWindowKind } from '@iphone-life-os/contracts';
import './styles.css';

type Page = 'overview'|'codex'|'clipper'|'health'|'finance';
type Navigate = (_page: Page) => void;
type Usage = ReturnType<typeof UnifiedUsage.parse>;
const categories: {id:Page; label:string; note:string}[] = [{id:'codex',label:'Codex',note:'Usage & limits'},{id:'clipper',label:'Clipper',note:'Source unavailable'},{id:'health',label:'Health',note:'HealthKit required'},{id:'finance',label:'Finance',note:'Import required'}];
const API = import.meta.env.VITE_API_URL || '';

function App() {
 const [page,setPage]=useState<Page>('overview'); const [overview,setOverview]=useState<Overview>(); const [codex,setCodex]=useState<CodexFixture>(); const [usage,setUsage]=useState<Usage>(); const [error,setError]=useState('');
 useEffect(()=>{ let alive=true;
   Promise.all([globalThis.fetch(`${API}/api/overview`).then(r=>{if(!r.ok)throw Error('Overview unavailable');return r.json()}),globalThis.fetch(`${API}/api/codex`).then(r=>{if(!r.ok)throw Error('Codex unavailable');return r.json()}),globalThis.fetch(`${API}/api/usage`).then(r=>{if(!r.ok)throw Error('Usage unavailable');return r.json()}).then(value=>UnifiedUsage.parse(value)).catch(()=>undefined)])
    .then(([o,c,u])=>{ const parsedOverview=parseOverview(o); const parsedCodex=parseCodexFixture(c); if(alive){setOverview(parsedOverview);setCodex(parsedCodex);if(u)setUsage(u)} })
    .catch(e=>{if(alive)setError(e instanceof Error ? `API response invalid or unavailable: ${e.message}` : 'API response invalid or unavailable')});
   return ()=>{alive=false};
 },[]);
 const loading=!overview||!codex;
 return <div className="app"><aside><h1>◈ Life OS</h1><small>private command center</small><nav><button className={page==='overview'?'selected':''} onClick={()=>setPage('overview')}>Overview</button>{categories.map(c=><button key={c.id} className={page===c.id?'selected':''} onClick={()=>setPage(c.id)}>{c.label}<span>{c.note}</span></button>)}</nav><p className="privacy">Sources stay authoritative</p></aside><main><header><div><span className="eyebrow">READ-ONLY · DEMO DATA</span><h2>{page==='overview'?'Signal overview':categories.find(c=>c.id===page)?.label}</h2></div><span className="fresh">● {loading?'Loading…':error?'Error':'Demo data · fresh'}</span></header>{error&&<div role="alert" className="error">{error}. Start the API with <code>npm run api</code>.</div>}{error?null:loading?<section className="panel">Loading verified API data…</section>:page==='overview'?<OverviewView data={overview!} usage={usage} go={setPage}/>:page==='codex'?<CodexView data={codex!}/>:<Blocked category={categories.find(c=>c.id===page)!.label}/>}<footer>Demo data only · no credentials, health samples, or financial records are stored here.</footer></main></div>
}
function OverviewView({data,usage,go}:{data:Overview;usage?:Usage;go:Navigate}){return <><section className="attention"><b>Current attention</b><h3>Codex session is {data.codex.status}</h3><p>Observed activity from the typed API contract. No action required.</p></section><section className="grid">{categories.map(c=><button className="card" key={c.id} onClick={()=>go(c.id)}><b>{c.label}</b><span>{c.id==='codex'?`${data.codex.usage5h.value}% of 5-hour window`:c.note}</span><small>{c.id==='codex'?'Source: demo-codex-fixture':'Source: unavailable'}</small></button>)}</section>{usage&&<CombinedUsage usage={usage}/>}</>}
function CombinedUsage({usage}:{usage:Usage}) { return <section className="usage-section"><div className="section-heading"><div><span className="eyebrow">ACCOUNT USAGE</span><h3>Codex + Claude limits</h3></div><small>Separate providers · never summed</small></div><div className="provider-grid">{(['codex','claude'] as Provider[]).map(provider=><ProviderCard key={provider} provider={provider} usage={usage}/>)}</div></section> }
function ProviderCard({provider,usage}:{provider:Provider;usage:Usage}) { const connector=usage.connectors[provider] ?? 'unavailable'; return <article className="provider-card"><div className="provider-title"><h4>{provider==='codex'?'Codex':'Claude'}</h4><span className={`state state-${connector}`}>{connector.replace('_',' ')}</span></div><p className="provider-note">{provider==='codex'?'Account-level shared agentic pool where supported.':'Claude Pro/Max shared limits across Claude and Claude Code; API billing is not implied.'}</p><div className="window-list">{(['five_hour','seven_day'] as UsageWindowKind[]).map(kind=><UsageRow key={kind} usage={usage} provider={provider} kind={kind}/>)}</div><small className="connector-meta">Connector: {connector} · generated {formatDate(usage.generatedAt)}</small></article> }
function UsageRow({usage,provider,kind}:{usage:Usage;provider:Provider;kind:UsageWindowKind}) { const w=usage.windows.find(x=>x.provider===provider&&x.window===kind); const estimate=usage.estimates.find(x=>x.provider===provider&&x.window===kind); const label=kind==='five_hour'?'5-hour window':'7-day window'; if(!w||w.availability==='unavailable') return <div className="window-row unavailable"><div><b>{label}</b><span>Unavailable · no observed value</span></div><strong>—</strong></div>; const p=w.usedPercent; return <div className="window-row"><div><b>{label}</b><span>{w.provenance.official?'Official observed':'Nonofficial estimate'} · {w.provenance.source}</span><span>{w.provenance.freshness} · quality {w.provenance.quality} · {w.provenance.connectorState}</span>{w.resetAt&&<span>Resets {formatDate(w.resetAt)}</span>}{estimate&&<span className="estimate">Nonofficial estimate: {estimate.confidence==='insufficient'?'insufficient history':`${estimate.confidence} confidence · ${estimate.sampleSpanHours}h sample`}</span>}</div><strong>{p===undefined?'—':`${p}%`}</strong></div> }
function formatDate(value:string){return new Date(value).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function CodexView({data}:{data:CodexFixture}){return <><section className="attention"><b>Current session · observed</b><h3>{data.session.status} · {data.session.model}</h3><p>{data.session.workspace} · source {data.session.status==='active'?'local session event':'unavailable'}</p></section><section className="grid metrics"><Metric label="5-hour window" value={`${data.usage.fiveHour.value}%`} meta="observed"/><Metric label="Weekly window" value={`${data.usage.weekly.value}%`} meta="observed"/><Metric label="Limit forecast" value={data.estimate.range} meta={`estimate · ${Math.round(data.estimate.confidence*100)}% confidence`}/><Metric label="Data age" value="4 min" meta="fresh · 15 min polling otherwise"/></section><section className="panel"><b>Why this estimate?</b><p>{data.estimate.explanation}</p><small>Inputs: observed usage trend · quality: estimated · source: {data.estimate.provenance.source}</small></section></>}
function Metric({label,value,meta}:{label:string;value:string;meta:string}){return <div className="card metric"><small>{label}</small><strong>{value}</strong><span>{meta}</span></div>}
function Blocked({category}:{category:string}){return <section className="panel blocked"><b>{category} · SOURCE BLOCKER</b><h3>Connect an authoritative source to begin</h3><p>This honest placeholder shows no invented metrics. Connector discovery and permissions are required.</p><span>Unavailable · quality unavailable · freshness unknown</span></section>}
export default App;
