import type { FinanceConnectorDescriptor } from '@iphone-life-os/contracts';

export const financeConnectors = [
  {
    id: 'sparkasse_leipzig',
    displayName: 'Sparkasse Leipzig',
    accessMethod: 'regulated_open_banking',
    provider: 'Enable Banking',
    enabled: false,
    requiresExplicitOptIn: true,
    risk: 'consent_required',
    recommendation: 'Configure the Sparkasse Leipzig institution and complete one-time Enable Banking consent before enabling; keep statement import as the fallback.',
  },
  {
    id: 'revolut_personal',
    displayName: 'Revolut Personal',
    accessMethod: 'regulated_open_banking',
    provider: 'Enable Banking',
    enabled: false,
    requiresExplicitOptIn: true,
    risk: 'consent_required',
    recommendation: 'Configure the personal Revolut institution and complete one-time Enable Banking consent before enabling; keep statement import as the fallback.',
  },
  {
    id: 'revolut_business',
    displayName: 'Revolut Business',
    accessMethod: 'official_oauth',
    provider: 'Official Revolut Business API',
    enabled: false,
    requiresExplicitOptIn: true,
    risk: 'account_eligibility_required',
    recommendation: 'Register an eligible Revolut Business app and complete official OAuth before enabling; Revolut review may delay access.',
  },
  {
    id: 'trade_republic',
    displayName: 'Trade Republic',
    accessMethod: 'manual_import',
    provider: 'Manual CSV/PDF import',
    enabled: false,
    requiresExplicitOptIn: true,
    risk: 'manual_import_only',
    recommendation: 'Permanent manual CSV/PDF import only; do not use private APIs or imply a live connector.',
  },
  {
    id: 'paypal_personal',
    displayName: 'PayPal Personal',
    accessMethod: 'official_oauth',
    provider: 'Official PayPal Transaction Search API',
    enabled: false,
    requiresExplicitOptIn: true,
    risk: 'account_eligibility_required',
    recommendation: 'Verify account and reporting-scope eligibility, then implement server-side OAuth and Transaction Search; otherwise keep PayPal unavailable or use a manual export.',
  },
] as const satisfies readonly FinanceConnectorDescriptor[];
