import { describe, expect, it } from 'vitest';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import type { ChildProcess } from 'node:child_process';
import { normalizeWindow, type UsageHistoryEntry } from '@iphone-life-os/contracts';
import { projectUsage } from './projection.js';
import { ingestClaudeStatusline } from './claude-ingest.js';
import { mapCodexResponse, codexSpawnSpec, createCodexTransport } from './codex-adapter.js';
import { UsageHistory } from './history.js';
const t=(n:number)=>new Date(Date.UTC(2026,0,1,0,n)).toISOString();
const entry=(n:number, usedPercent:number): UsageHistoryEntry => ({provider:'codex',window:'five_hour',durationMinutes:300,usedPercent,observedAt:t(n)});
describe('usage contracts and projection',()=>{
 it('separates providers and marks estimates nonofficial',()=>{const a=normalizeWindow({usedPercentage:20,resetsAt:1700000000},'codex','five_hour','x',t(0)); const b=normalizeWindow({usedPercentage:40,resetsAt:'2026-01-01T05:00:00Z'},'claude','five_hour','x',t(0)); expect(a.provider).not.toBe(b.provider); expect(projectUsage([{...a,usedPercent:20,observedAt:t(0),durationMinutes:300},{...a,usedPercent:30,observedAt:t(5),durationMinutes:300}]).official).toBe(false);});
 it('selects a spawnable Codex command on Windows and POSIX',()=>{expect(codexSpawnSpec('win32','cmd.exe')).toEqual({command:'cmd.exe',args:['/d','/s','/c','codex.cmd','app-server']}); expect(codexSpawnSpec('darwin')).toEqual({command:'codex',args:['app-server']});});
 it('maps the current Codex app-server rateLimits envelope and numeric reset timestamp',()=>{const result=mapCodexResponse({rateLimits:{primary:{usedPercent:1,windowDurationMins:10080,resetsAt:1786777259},secondary:null}}); expect(result.connectorState).toBe('healthy'); expect(result.windows).toEqual([{minutes:10080,usedPercent:1,resetAt:'2026-08-15T07:00:59.000Z'}]);});
 it('rejects coerced nonnumeric Codex usage values',()=>{for(const usedPercent of [false,'',null]) expect(mapCodexResponse({rateLimits:{primary:{usedPercent,windowDurationMins:300}}}).windows).toEqual([]);});
 it('rejects unsupported Codex rate-limit durations instead of relabeling them',()=>{expect(mapCodexResponse({rateLimits:{primary:{usedPercent:1,windowDurationMins:60}}}).windows).toEqual([]);});
 it('fails the whole Codex response closed on duplicate supported windows',()=>{expect(mapCodexResponse({rateLimits:{primary:{usedPercent:1,windowDurationMins:300},windows:[{usedPercent:2,windowDurationMins:300}]}})).toMatchObject({connectorState:'unavailable',windows:[]});});
 it('fails closed on an invalid numeric Codex reset timestamp',()=>{expect(mapCodexResponse({rateLimits:{primary:{usedPercent:1,windowDurationMins:300,resetsAt:Number.POSITIVE_INFINITY}}})).toMatchObject({connectorState:'healthy',windows:[{minutes:300,usedPercent:1}]});});
 it('terminates the Codex transport when an unterminated protocol frame exceeds its bound',async()=>{const stdout=new PassThrough(); const stdin=new PassThrough(); const emitter=new EventEmitter() as EventEmitter & Partial<ChildProcess> & {killed:boolean}; emitter.stdout=stdout; emitter.stdin=stdin; emitter.killed=false; emitter.kill=(()=>{emitter.killed=true; return true;}) as ChildProcess['kill']; const request=createCodexTransport(emitter as ChildProcess); const response=request({method:'initialize',params:{}}); stdout.write('x'.repeat(1_048_577)); await expect(response).rejects.toThrow('protocol'); expect(emitter.killed).toBe(true);});
 it('unavailable windows remain unavailable',()=>expect(normalizeWindow({},'codex','seven_day','x',t(0)).availability).toBe('unavailable'));
 it('normalizes documented Claude shape and strips sensitive fields',()=>{const w=ingestClaudeStatusline({rate_limits:{five_hour:{used_percentage:12,resets_at:'2026-01-01T05:00:00Z',token:'secret'},seven_day:{used_percentage:3,resets_at:'2026-01-08T00:00:00Z'}}},t(0)); expect(w.map(x=>x.usedPercent)).toEqual([12,3]); expect(JSON.stringify(w)).not.toContain('secret');});
 it('does not project decreases, zero velocity, or mixed providers',()=>{const a={provider:'codex' as const,window:'five_hour' as const,durationMinutes:300,usedPercent:20,observedAt:t(0),resetAt:t(300)}; expect(projectUsage([a,{...a,usedPercent:10,observedAt:t(5)}]).confidence).toBe('insufficient'); expect(projectUsage([a,{...a,provider:'claude',usedPercent:30,observedAt:t(5)}]).confidence).toBe('insufficient');});
 it('does not project to a reset when no valid future reset boundary exists',()=>{const withoutReset=entry(0,10); expect(projectUsage([withoutReset,entry(5,20)],new Date(t(6))).confidence).toBe('insufficient'); const expired={...entry(0,10),resetAt:t(4)}; expect(projectUsage([expired,{...expired,usedPercent:20,observedAt:t(5)}],new Date(t(6))).confidence).toBe('insufficient');});
 it('retains bounded valid history and fails closed on corruption',async()=>{const dir=await mkdtemp(join(tmpdir(),'usage-')); const file=join(dir,'history.jsonl'); const store=new UsageHistory(file,2,60*60*1000,()=>Date.parse(t(2))); await store.add(entry(0,10)); await store.add(entry(1,20)); await store.add(entry(2,30)); expect((await store.list()).map(x=>x.usedPercent)).toEqual([20,30]); const raw=await readFile(file,'utf8'); expect(raw).not.toContain('secret'); await writeFile(file,raw+'not-json\\n'); expect(await store.list()).toEqual([]);});
});
